version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'chore(deps)'
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
