name: Storybook
on:
  push:
    branches:
      - develop

jobs:
  storybook:
    name: storybook
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
      - name: Setup Aikido safe-chain
        run: npm i -g @aikidosec/safe-chain
      - name: Install dependencies
        run: aikido-npm ci --ignore-scripts
      - name: Build Storybook
        run: npm run storybook:build
      - name: Upload Storybook artifacts
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: storybook-static
      - name: Deploy Storybook to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        with:
          token: ${{ github.token }}
